version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: notebook
    container_name: notebook
    restart: unless-stopped
    working_dir: /mnt/c/notebook
    volumes:
      - //c/notebook:/mnt/c/notebook
    networks:
      - notebook

  db:
    image: mysql:5.7
    container_name: notebook-db
    restart: unless-stopped
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: notebook
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - notebook

  nginx:
    image: nginx:alpine
    container_name: notebook-nginx
    restart: unless-stopped
    ports:
      - 8188:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - notebook

networks:
  notebook:
    driver: bridge